language: cpp
compiler: clang

matrix:
  include:
    - os: linux
      services: docker
      env:
        - DOCKER_IMAGE=thijswithaar/debian:sid

  include:
    - os: linux
      services: docker
      env:
        - DOCKER_IMAGE=thijswithaar/fedora:rawhide

  include:
    - os: linux
      services: docker
      env:
        - DOCKER_IMAGE=thijswithaar/ubuntu:devel

  include:
    - os: linux
      services: docker
      env:
        - DOCKER_IMAGE=thijswithaar/arch:latest

script:
 - export DOCKER_BUILD_DIR=${TRAVIS_BUILD_DIR}
 - docker run --user $(id -u):$(id -g) -v ${TRAVIS_BUILD_DIR}:${DOCKER_BUILD_DIR} -w ${DOCKER_BUILD_DIR} ${DOCKER_IMAGE} ${DOCKER_BUILD_DIR}/build.sh build

deploy:
 provider: releases
 tag_name: ${TRAVIS_TAG}
 target_commitish: "master"
 name: "It's a release"
 api_key: ${GithubToken}
 file_glob: true
 file: "${TRAVIS_BUILD_DIR}/deploy/*"
 overwrite: true
 skip_cleanup: true
 draft: false
 on:
  tags: true
